In [5]:
#Numpy Basic Operations

import numpy as np

a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [6]:
print (type(a))

<class 'numpy.ndarray'>


In [8]:
print(a.shape)

(4,)


In [12]:
print(a[1])

4


In [19]:
a2darray = np.array([[1,2,3],[4,5,6]])

print(a2darray)
print(a2darray.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
print(type(a2darray))

<class 'numpy.ndarray'>


In [22]:
a2darray[0,2]

3

In [23]:
a= np.array([1,2,3])

In [24]:
a.dtype

dtype('int32')

In [25]:
b = np.array([1,2,3,4.5565])

In [26]:
b.dtype

dtype('float64')

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [29]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [30]:
np.ones((1,3))

array([[ 1.,  1.,  1.]])

In [31]:
np.empty((1,4))

array([[ 0.25,  0.5 ,  0.75,  1.  ]])

In [32]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [61]:
a =np.array([[1,2],[2,3]])

In [62]:
a.shape

(2, 2)

In [39]:
a.ravel()

array([1, 2, 2, 3, 4, 5])

In [63]:
a.min()

1

In [64]:
a

array([[1, 2],
       [2, 3]])

In [65]:
a.sum(axis=0)

array([3, 5])

In [66]:
a.sum(axis=1)

array([3, 5])

In [67]:
np.sqrt(a)

array([[ 1.        ,  1.41421356],
       [ 1.41421356,  1.73205081]])

In [59]:
b = np.array([[1,2],[2,3]])

In [68]:
a.dot(b)

array([[ 5,  8],
       [ 8, 13]])

In [69]:
a.dot(b)

array([[ 5,  8],
       [ 8, 13]])

In [33]:
np.diag((1,2,3,5,6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [13]:
s = np.array([[1,2,3],[2,4]])


In [14]:
s.ndim

1

In [15]:
s.itemsize

8

In [10]:
s.dtype

dtype('int32')

In [16]:
a.size

4

In [17]:
s.size

2

In [70]:
#Numpy Slicing, Iterations, Indexing Arrays 






